I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 397, in script
    "To be continued"
  File "renpy/common/000window.rpy", line 114, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 69, in _window_show
    renpy.with_statement(trans)
IOError: Couldn't find file 'ruins.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 397, in script
    "To be continued"
  File "renpy/ast.py", line 871, in execute
    statement_name("say")
  File "renpy/ast.py", line 47, in statement_name
    i(name)
  File "renpy/common/000window.rpy", line 114, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 69, in _window_show
    renpy.with_statement(trans)
  File "renpy/exports.py", line 1653, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "renpy/display/core.py", line 2800, in do_with
    clear=clear)
  File "renpy/display/core.py", line 3376, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs) # type: ignore
  File "renpy/display/core.py", line 4096, in interact_core
    renpy.audio.audio.periodic()
  File "renpy/audio/audio.py", line 1166, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "renpy/audio/audio.py", line 1144, in periodic_thread_main
    periodic_pass()
  File "renpy/audio/audio.py", line 1086, in periodic_pass
    c.periodic()
  File "renpy/audio/audio.py", line 517, in periodic
    topf = load(filename)
  File "renpy/audio/audio.py", line 70, in load
    rv = renpy.loader.load(fn)
  File "renpy/loader.py", line 820, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'ruins.mp3'.

Windows-10-10.0.19041 AMD64
Ren'Py 7.5.0.22062402
Bystander 1.0
Thu Jul 14 22:58:14 2022
