I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 215, in script
    show tom sad left
Exception: Image 'tom sad' does not accept attributes 'left'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 215, in script
    show tom sad left
  File "renpy/ast.py", line 1388, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1358, in show_imspec
    atl=atl)
  File "renpy/exports.py", line 686, in show
    if not base.find_target() and renpy.config.missing_show:
  File "renpy/display/image.py", line 413, in find_target
    self.target = target._duplicate(a)
  File "renpy/display/core.py", line 397, in _duplicate
    args.extraneous()
  File "renpy/display/core.py", line 267, in extraneous
    " ".join(self.args),
Exception: Image 'tom sad' does not accept attributes 'left'.

Windows-10-10.0.19041 AMD64
Ren'Py 7.5.0.22062402
Bystander 1.0
Thu Jul 14 20:49:15 2022
